### ISSUE TITLE
While GoodbyeDPI is active Reddit gets messed up

### ISSUE THREAD

**Issue by sanon** [ValdikSS/GoodbyeDPI#202] opened 2021-01-25 07:29 UTC
Hello,
I've been using GoodbyeDPI for quite some time. Thanks for the great program. 
For the last 2 days if it's active Reddit doesn't load properly. This is how it looks:
![2021-01-24 08 40 06 www reddit com ca1b531491a4](https://user-images.githubusercontent.com/6686059/105672672-dea0a300-5ef5-11eb-9dc1-5760c1f99fa2.jpg)
As soon as I close it, the page loads normally after a refresh.
Any help is much appreciated, thanks. 

My system:
GoodbyeDPI 0.1.6
Vivaldi 3.5.2115.87 (Stable channel) (64-bit)  (Same problem in Opera and Firefox too)
NVidia GeForce GT 425M
Windows 10 Home 64bit, OS Version 1909
Active extensions:
Lastpass

**Describe the bug / Опишите проблему**
A clear and concise description of what the bug is. If the issue about software incompatibility, include your operating system version and software name/version.
Подробно опишите, в чём заключается проблема. Если проблема касается совместимости с другими программами, укажите версию вашей операционной системы, имя и версию программы.

**To Reproduce / Шаги воспроизведения проблемы**

**Expected behavior / ожидаемое поведение программы**
Подробно опишите, как вы ожидаете, чтобы программа работала.

**Actual behavior / текущее поведение программы**
Подробно опишите, что происходит с программой на текущий момент.

**Screenshots / Скриншоты**
Если необходимо, добавьте скриншоты, объясняющие проблему.

**Additional context / дополнительная информация**

**Comment by LIMUNADE** [comment] 2021-01-25 15:07
My issue even worse.
![image](https://user-images.githubusercontent.com/20593218/105723649-732ff300-5f40-11eb-962e-876be58237fe.png)

Yet on Tor Browser it's works normal. 
![image](https://user-images.githubusercontent.com/20593218/105723730-90fd5800-5f40-11eb-98a5-5b7fe76d62c1.png)

**Comment by iripu** [comment] 2021-01-25 15:21
> My issue even worse.

Facing exact same issue.

**Comment by iripu** [comment] 2021-01-25 15:29
> this is not a GoodbyeDPI issue, but an issue with websites' web server/balancer/SSL endpoint fragmented TLS packets, enforced by GoodbyeDPI as one of the DPI circumvention method

Full response from he developer:
https://github.com/ValdikSS/GoodbyeDPI/issues/200#issuecomment-766433591

**Comment by iripu** [comment] 2021-01-25 15:41
Had issue with reddit, fixed with -4 option.

**Comment by bbley1** [comment] 2021-01-25 19:57
> 
> 
> Had issue with reddit, fixed with -4 option.

thx
-4 --wrong-chksum -f 2
did the trick for me. now it works as before without any breakage.

**Comment by sanon** [comment] 2021-01-25 20:27
> > Had issue with reddit, fixed with -4 option.
> 
> thx
> -4 --wrong-chksum -f 2
> did the trick for me. now it works as before without any breakage.

Which one activates this option?
![Clipboard01](https://user-images.githubusercontent.com/6686059/105762023-e3e90680-5f64-11eb-9219-d6dff654b61d.jpg)

**Comment by bbley1** [comment] 2021-01-25 20:50
@sanon none of them. make a copy of 4_fakepacket_all.cmd and then right click on it > open with notepad

change the 7th line as below
start "" goodbyedpi.exe -4 --wrong-chksum -f 2

though i dont claim this would work with every ISP. you can try other options as well
https://github.com/ValdikSS/GoodbyeDPI/#user-content-how-to-use

**Comment by sanon** [comment] 2021-01-25 21:28
@bbley1 Thank you.

**Comment by LIMUNADE** [comment] 2021-02-01 16:53
Unfortunately doesn't work for me. It's daunting to use gbd now, with all this _handshaking_ issues.

**Comment by dst27** [comment] 2021-02-28 13:46
@sanon please consider closing this issue now since Reddit has fixed the regression on their server software.
Reddit and all other sites I was aware of with the buggy server software seem to have fixed it now and work with GoodbyeDPI just like before.

**Closed** 2021-02-28 19:02 UTC
