### ISSUE TITLE
Secure Connection Failed

### ISSUE THREAD

**Issue by wankio** [ValdikSS/GoodbyeDPI#200] opened 2020-12-17 16:06 UTC
I can't not access this website https://wololo.net while GoodbyeDPI is enabled, i think maybe there have more website have this problem but i'm don't know it yet

**Comment by kotomaxibon** [comment] 2021-01-18 13:06
A lot of websites are giving me Secure connection failed errors since about a month ago.

**Comment by hstdra** [comment] 2021-01-21 08:12
Yes, now https://stackoverflow.com also.

**Comment by lynxtaa** [comment] 2021-01-21 12:08
I have the same problem.

It seems to be working OK when using `-2` option

**Comment by ValdikSS** [comment] 2021-01-21 18:59
If you use goodbyedpi with default parameters (or `-1` or `-e` set to any value), this is most likely #4 or #64.
To make sure you can [capture Wireshark dump](https://github.com/ValdikSS/GoodbyeDPI/wiki/How-to-make-traffic-dump-with-Wireshark) and send it to me at iam@valdikss.org.ru.

This is not a GoodbyeDPI issue per se, this is your ISP.

**Comment by evilandfox** [comment] 2021-01-22 15:59
Today I caught ERR_CERT_COMMON_NAME_INVALID troubles with Gitlab. It taked a lot of time till I resolved the problem after stopping goodbyedpi.exe process)

**Comment by Trojaner** [comment] 2021-01-23 03:58
It looks like many sites (e.g. gitlab, preview.reddit.com, stackoverflow.com) started to have issues with goodbyedpi now.
Example: https://community.letsencrypt.org/t/stackoverflow-showing-outdated-letsencrypt-certs-why/143308/

Are you sure this is related to the ISP? Would be a coincidence if so many people suddenly face this issue...

**Comment by jaepil-choi** [comment] 2021-01-23 04:06
Also experienced the exact same issue. I was freaking out because this was happening only on one PC, only on certain websites. Thought it was some kind of serious security breach. 

Relieved to find out goodbyedpi was the cause, but why is it happening just now? I had no problem accessing Stackoverflow with goodbyedpi turned on until yesterday.

**Comment by furkandeger** [comment] 2021-01-23 10:18
> It looks like many sites (e.g. gitlab.com, reddit.com, stackoverflow.com) suddenly started having issues with goodbyedpi.
> Example: https://community.letsencrypt.org/t/stackoverflow-showing-outdated-letsencrypt-certs-why/143308/
> 
> Are you sure this is related to the ISPs? Would be a coincidence if so many people suddenly face this issue...
> 
> Stackoverflow sending me expired certificates:
> ![image](https://user-images.githubusercontent.com/1809172/105568175-72cd0780-5d48-11eb-81ad-a4e3dc658df1.png)
> 
> Reddit certificate is not expired but still gets rejected:
> ![image](https://user-images.githubusercontent.com/1809172/105568187-7eb8c980-5d48-11eb-80ae-f6bd1991094b.png)
> 
> Both issues are solved instantly when shutting down goodbyedpi.
> 
> Note: issue only happens with some sites, most of the sites work without issues with https.

I can confirm this. I also don't think it's a coincidence and I don't think it's related to the ISPs.

**Comment by bbley1** [comment] 2021-01-23 13:40
Tried PowerTunnel. When i enable "Full chunking mode" same thing happens with PowerTunnel as well. Only some https sites like reddit returns certification error even though theyre not censored in my country. Adding broken cert domains to whitelist is a good workaround for now.

**Comment by furkandeger** [comment] 2021-01-23 15:21
> Tried PowerTunnel. When i enable "Full chunking mode" same thing happens with PowerTunnel as well. Only some https sites like reddit returns certification error even though theyre not censored in my country. Adding broken cert domains to whitelist is a good workaround for now.

Oh forgive I haven't tried "full chunking mode" as I am not aware what exactly it does and it does the job without it enabled.

**Comment by wankio** [comment] 2021-01-23 15:54
> 
> 
> Yes, now https://stackoverflow.com also.

yeah, i'm thought my pc is broken :D until i shut GDPI down, reddit can't load any images

**Comment by aca** [comment] 2021-01-23 16:22
Experiencing same issue with https://github.com/farukuzun/notsodeep

**Comment by asrdri** [comment] 2021-01-23 20:52
Getting the same issue for a few days now on reddit. Noticed that it's not always about expired certificates, but just wrong certificates. Error is `NET::ERR_CERT_COMMON_NAME_INVALID`
Example: I'm opening an image located at i.redd.it domain and it tries to use a valid certificate but issued for `*.reddit.com`, not for `*.redd.it`. Using a VPN solves the issue for some time due to SSL cache I guess.

**Comment by WPMGPRoSToTeMa** [comment] 2021-01-24 01:02
@ValdikSS is it possible to adapt blacklist option to HTTPS fragmentation? So, will fragmentation hack work if it is applied only to the packet with SNI provided?

**Comment by ValdikSS** [comment] 2021-01-24 21:16
As stated in https://github.com/ValdikSS/GoodbyeDPI/issues/200#issuecomment-764866276, this is not a GoodbyeDPI issue, but an issue with websites' web server/balancer/SSL endpoint fragmented TLS packets, enforced by GoodbyeDPI as one of the DPI circumvention method, or (sometimes) with your ISP.
This issue is known, [documented](https://github.com/ValdikSS/GoodbyeDPI/blob/master/README.md#known-issues) in the README and was discussed in #4 and #64.

Why did it started to happen much more in the previous week? I can't say for sure, but most probably due to web server/balancer/SSL endpoint software or hardware upgrade, which introduced incompatibility with fragmented packets.

The best you, as a casual user, can do is to contact websites' administrators and tell them about fragmented packets issue. Don't mention GoodbyeDPI, because this is really just a network misconfiguration on their side which could be triggered in a usual browser, on not-typically-configured networks, under some conditions (low MTU, low buffer sizes on embedded hardware, etc).
I, as a developer, can introduce TLS SNI filter. Actually I have one, this is one of the features I wanted for a long time, but as you can see, I don't work on GoodbyeDPI much. It needs to be revamped and commited, which I will occasionally do.

Please do not flood in this issue. Remember that Github issues are for **application issues only**, and this is not one of those. You can discuss any GoodbyeDPI-related topics on NTC forum https://ntc.party/c/community-software/goodbyedpi.

**Comment by iripu** [comment] 2021-01-25 15:40
Had issue with reddit, fixed with -4 option.

**Comment by arnobk** [comment] 2021-01-27 12:32
+1

**Comment by ValdikSS** [comment] 2021-02-15 15:43
Currently I can reproduce this issue only on Gitlab, on https://about.gitlab.com and https://assets.gitlab-static.net, while Reddit, Stackoverflow and Wololo mentioned in GoodbyeDPI issue work fine for me.

Just submitted the information to Fastly and to Gitlab, we'll see how it goes.

**Comment by qweqwe567** [comment] 2021-02-18 01:06
I don't know if it's related to this, but I started getting "SSL handshake failed" on 4chan and some other sites. (turkish isp)

**Comment by ValdikSS** [comment] 2021-02-22 21:01
Fastly fixed the issue.

**Closed** 2021-12-24 18:55 UTC

**Comment by diblodock** [comment] 2023-12-26 17:53
> However, it does not work in Chrome 121 (dev version), while it works in Chrome 120. For any site with any option.
> 
> UPD: Because of this [developer.chrome.com/blog/chrome-121-beta#x25519kyber768_key_encapsulation_for_tls](https://developer.chrome.com/blog/chrome-121-beta#x25519kyber768_key_encapsulation_for_tls)
> 
> **chrome://flags/#enable-tls13-kyber**
> 
> **_Currently_**, it's possible to disable this flag.

thank you, it helped me
