### ISSUE TITLE
goodbyedpi not working on some websites

### ISSUE THREAD

**Issue by AkoSuminoe25** [ValdikSS/GoodbyeDPI#231] opened 2021-12-11 12:27 UTC
As I mentioned in the title, GoodbyeDpi 1.6 version does not work on some websites, for example nhentai etc. Can you help please. Thanks in advance. (sorry for my english)

**Comment by CloudSnowPony** [comment] 2021-12-23 17:45
goodbyedpi stopped working for me. It used to work perfectly. Now nothing works!!!

**Comment by ValdikSS** [comment] 2021-12-24 18:55
@AkoSuminoe25 doesn't seem to be a server-related issue, it works for me.

**Comment by AkoSuminoe25** [comment] 2021-12-26 16:20
well now i looked again and it goes in but very slow. Do you suggest that I run it from the commands there to take away this slowness? really sooo slow

**Comment by ValdikSS** [comment] 2021-12-26 16:53
Try this version. Just launch the file without any options: https://github.com/ValdikSS/GoodbyeDPI/actions/runs/1624450860

**Comment by ValdikSS** [comment] 2022-01-01 12:12
I would guess that the issue is fixed with `--auto-ttl` and everything.
Tell if the issue still applies to the latest version.

**Closed by ValdikSS** 2022-01-01 12:12 UTC
